source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'just-the-docs', '~> 0.10'
gem 'jekyll-remote-theme', '~> 0.4'
gem 'jekyll-seo-tag', '~> 2.8'
gem 'jekyll-sitemap', '~> 1.4'
gem 'kramdown-parser-gfm', '~> 1.1'
gem 'webrick', '~> 1.8'

group :jekyll_plugins do
  gem 'jekyll-remote-theme'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
end

platforms :jruby do
  gem 'nokogiri', '~> 1.13'
  gem 'css-parser'
end
