source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'jekyll-remote-theme', '~> 0.4'
gem 'jekyll-seo-tag', '~> 2.8'
gem 'kramdown-parser-gfm', '~> 1.1'
gem 'webrick', '~> 1.8'

group :jekyll_plugins do
  gem 'jekyll-remote-theme'
  gem 'jekyll-seo-tag'
end
